CREATE TABLE IF NOT EXISTS digimon (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    atributo VARCHAR(100) NOT NULL,
    nivel VARCHAR(100) NOT NULL,
    familia CHAR(2) NOT NULL,
    imagem VARCHAR(300) NOT NULL
);



INSERT INTO digimon (nome, atributo, nivel, familia, imagem)
VALUES ('Agumon', 'Vacina', 'Criança', 'DR', 'https://digimon.net/cimages/digimon/agumon.jpg');