CREATE TABLE IF NOT EXISTS digimon (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    poder INT NOT NULL,
    atributo VARCHAR(100) NOT NULL,
    nivel VARCHAR(100) NOT NULL,
    familia CHAR(2) NOT NULL,
    imagem VARCHAR(300) NOT NULL,
    dataRegistro DATE NOT NULL
);



INSERT INTO digimon (nome, poder, atributo, nivel, familia, imagem, dataRegistro)
VALUES ('Agumon', 10, 'Vacina', 'Criança', 'DR', 'https://digimon.net/cimages/digimon/agumon.jpg', '2026-08-29');